stages:
    - build
    - test
    - push
    - clean
    - deploy

build_image_latest:
    stage: build
    only:
        - master
        - branches
    script:
        - docker build --build-arg DOCS_URL=https://stage-webcoos-docs.srv.axds.co/ --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg WEBCOOS_API_TOKEN=$WEBCOOS_API_TOKEN -t $CI_PROJECT_NAME:$CI_PIPELINE_ID .

build_image_tag:
    stage: build
    only:
        - tags
    script:
        - docker build --build-arg DOCS_URL=https://webcoos-docs.srv.axds.co/ --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg WEBCOOS_API_TOKEN=$WEBCOOS_PROD_API_TOKEN --build-arg WEBCOOS_API_URL=https://app.webcoos.org/webcoos/api -t $CI_PROJECT_NAME:$CI_PIPELINE_ID .

test:
    stage: test
    image: $CI_PROJECT_NAME:$CI_PIPELINE_ID
    before_script:
        # http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd
        - npm ci --unsafe-perm
    script:
        - npm test

push_latest:
    needs: ["build_image_latest"]
    stage: push
    only:
        - master
    script:
        - docker tag $CI_PROJECT_NAME:$CI_PIPELINE_ID registry.axiom/$CI_PROJECT_NAME:latest
        - docker push registry.axiom/$CI_PROJECT_NAME:latest

push_tag:
    needs: ["build_image_tag"]
    stage: push
    only:
        - tags
    script:
        - docker tag $CI_PROJECT_NAME:$CI_PIPELINE_ID registry.axiom/$CI_PROJECT_NAME:$CI_BUILD_TAG
        - docker push registry.axiom/$CI_PROJECT_NAME:$CI_BUILD_TAG
        - docker tag $CI_PROJECT_NAME:$CI_PIPELINE_ID registry.axiom/$CI_PROJECT_NAME:prod
        - docker push registry.axiom/$CI_PROJECT_NAME:prod

clean_base:
    stage: clean
    script:
        - docker rmi --no-prune $CI_PROJECT_NAME:$CI_PIPELINE_ID

clean_latest:
    needs: ["push_latest"]
    stage: clean
    only:
        - master
    script:
        - docker rmi --no-prune registry.axiom/$CI_PROJECT_NAME:latest

clean_tag:
    needs: ["push_tag"]
    stage: clean
    only:
        - tags
    script:
        - docker rmi --no-prune registry.axiom/$CI_PROJECT_NAME:$CI_BUILD_TAG
        - docker rmi --no-prune registry.axiom/$CI_PROJECT_NAME:prod

deploy_stage:
    needs: ["push_latest"]
    stage: deploy
    only:
        - master
    script:
        - docker pull registry.axiom/ansible:latest
        - docker run --rm registry.axiom/ansible:latest ap apps-stage $CI_PROJECT_NAME --tags deploy
    environment:
        name: staging
        url: https://stage.webcoos.org/

deploy_prod:
    needs: ["push_tag"]
    stage: deploy
    only:
        - tags
    script:
        - docker pull registry.axiom/ansible:latest
        - docker run --rm registry.axiom/ansible:latest ap apps-prod $CI_PROJECT_NAME -e axds_project_site_version=$CI_BUILD_TAG --tags deploy
    environment:
        name: production
        url: https://www.webcoos.org/