services:

  app:
    image: "webcoos-project-site:latest"
    build:
      context:    .
      dockerfile: Dockerfile
    environment:
      TWOWOLVES_PUBLIC_WEBCOOS_API_TOKEN: "${VITE_PUBLIC_WEBCOOS_API_TOKEN}"
      TWOWOLVES_PUBLIC_WEBCOOS_API_URL: "${VITE_PUBLIC_WEBCOOS_API_URL}"
      TWOWOLVES_APP_MAPBOX_TOKEN: "${VITE_APP_MAPBOX_TOKEN}"
      TWOWOLVES_PUBLIC_FEEDBACK_URL: "${VITE_PUBLIC_FEEDBACK_URL}"
    ports:
     - 6173:80
