site:
    title: WebCOOS
    description: The project website for WebCOOS
helpEmail:
header:
    logoImage: /SECOORA_Horizontal_FullColor_Transparent.png
    logoAltText: SECOORA logo
    bannerText: WebCOOS
    menus:
        - label: Get Involved
          to: /get-involved
        - label: Cameras
          to: /cameras
        - label: Products
          to: /products
        - label: Documentation
          to: /docs
        - label: About
          to: /about
        - label: Feedback
          to: /feedback
footer:
    logoImage: /SECOORA_logo.png
    logoAltText: SECOORA logo
    contact:
        name: SECOORA
        address: |
          PO Box 13856
          Charleston, SC
          29422
#        tel: (555) 555-1234
        email: communications@secoora.org
#    linkLists:
#        - title: About
#          links:
#              - label: WebCOOS
#                to: /about
#              - label: SECOORA
#                to: https://secoora.org/about
