name: Build Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BUILDX_CACHE: /tmp/.buildx-cache
  CACHE_KEY: docker-webcoospush-buildx-

jobs:
  build-push:
    name: Build and test Docker Image
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          axiom/webcoos-project-site
        tags: |
          type=raw,value=latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ${ BUILDX_CACHE }
        key: ${ CACHE_KEY }${{ github.sha }}
        restore-keys: |
          ${ CACHE_KEY }

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DOCS_URL=${{ vars.DOCS_URL }}
          WEBCOOS_API_URL=${{ vars.WEBCOOS_API_URL }}
          WEBCOOS_API_TOKEN=${{ secrets.WEBCOOS_API_TOKEN }}
          FEEDBACK_URL=${{ secrets.FEEDBACK_URL }}
          MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
          GOOGLE_ANALYTICS_MEASUREMENT_ID=${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
        cache-from: type=local,src=${ BUILDX_CACHE }
        cache-to: type=local,dest=${ BUILDX_CACHE }
        outputs: type=docker

    - name: Run Docker Image in Background
      run: docker run -d -p 3000:3000 ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

    - name: Check that webcoos Docker Image will return a 200
      uses: ifaxity/wait-on-action@v1.1.0
      timeout-minutes: 1
      with:
        resource: http://localhost:3000

    - name: test
      run: docker run -d ${{ fromJSON(steps.meta.outputs.json).tags[0] }} bash -c 'npm ci --unsafe-perm && npm test'

  push:
    name: Push latest image to Docker Hub
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: build-push
    if: github.ref == 'refs/heads/main' && github.repository == 'WebCOOS/webcoos.org'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          axiom/webcoos-project-site
        tags: |
          type=raw,value=latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ${ BUILDX_CACHE }
        key: ${ CACHE_KEY }${{ github.sha }}
        restore-keys: |
          ${ CACHE_KEY }

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DOCS_URL=${{ vars.DOCS_URL }}
          WEBCOOS_API_URL=${{ vars.WEBCOOS_API_URL }}
          WEBCOOS_API_TOKEN=${{ secrets.WEBCOOS_API_TOKEN }}
          FEEDBACK_URL=${{ secrets.FEEDBACK_URL }}
          MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
          GOOGLE_ANALYTICS_MEASUREMENT_ID=${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
        cache-from: type=local,src=${ BUILDX_CACHE }
        cache-to: type=local,dest=${ BUILDX_CACHE }
